#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Tables.Sample.Resource", IsApplication=true)]

namespace Tables.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Xamarin.Tables.Resource.Animation.slide_in_left = Tables.Sample.Resource.Animation.slide_in_left;
			Xamarin.Tables.Resource.Animation.slide_in_right = Tables.Sample.Resource.Animation.slide_in_right;
			Xamarin.Tables.Resource.Animation.slide_out_left = Tables.Sample.Resource.Animation.slide_out_left;
			Xamarin.Tables.Resource.Animation.slide_out_right = Tables.Sample.Resource.Animation.slide_out_right;
			Xamarin.Tables.Resource.Drawable.dialog_disclosure = Tables.Sample.Resource.Drawable.dialog_disclosure;
			Xamarin.Tables.Resource.Drawable.dialog_expander_ic_minimized = Tables.Sample.Resource.Drawable.dialog_expander_ic_minimized;
			Xamarin.Tables.Resource.Id.LeftBtn = Tables.Sample.Resource.Id.LeftBtn;
			Xamarin.Tables.Resource.Id.LeftButtonLayout = Tables.Sample.Resource.Id.LeftButtonLayout;
			Xamarin.Tables.Resource.Id.LinearLayout01 = Tables.Sample.Resource.Id.LinearLayout01;
			Xamarin.Tables.Resource.Id.RightBtn = Tables.Sample.Resource.Id.RightBtn;
			Xamarin.Tables.Resource.Id.RightButtonLayout = Tables.Sample.Resource.Id.RightButtonLayout;
			Xamarin.Tables.Resource.Id.dialog_BoolField = Tables.Sample.Resource.Id.dialog_BoolField;
			Xamarin.Tables.Resource.Id.dialog_Button = Tables.Sample.Resource.Id.dialog_Button;
			Xamarin.Tables.Resource.Id.dialog_DisclosureField = Tables.Sample.Resource.Id.dialog_DisclosureField;
			Xamarin.Tables.Resource.Id.dialog_ImageLeft = Tables.Sample.Resource.Id.dialog_ImageLeft;
			Xamarin.Tables.Resource.Id.dialog_ImageRight = Tables.Sample.Resource.Id.dialog_ImageRight;
			Xamarin.Tables.Resource.Id.dialog_LabelField = Tables.Sample.Resource.Id.dialog_LabelField;
			Xamarin.Tables.Resource.Id.dialog_LabelSubtextField = Tables.Sample.Resource.Id.dialog_LabelSubtextField;
			Xamarin.Tables.Resource.Id.dialog_Panel = Tables.Sample.Resource.Id.dialog_Panel;
			Xamarin.Tables.Resource.Id.dialog_RadioButtonList = Tables.Sample.Resource.Id.dialog_RadioButtonList;
			Xamarin.Tables.Resource.Id.dialog_SliderField = Tables.Sample.Resource.Id.dialog_SliderField;
			Xamarin.Tables.Resource.Id.dialog_Spinner = Tables.Sample.Resource.Id.dialog_Spinner;
			Xamarin.Tables.Resource.Id.dialog_ValueField = Tables.Sample.Resource.Id.dialog_ValueField;
			Xamarin.Tables.Resource.Id.iFormFieldValue = Tables.Sample.Resource.Id.iFormFieldValue;
			Xamarin.Tables.Resource.Id.navContent = Tables.Sample.Resource.Id.navContent;
			Xamarin.Tables.Resource.Id.title = Tables.Sample.Resource.Id.title;
			Xamarin.Tables.Resource.Layout.dialog_achievements = Tables.Sample.Resource.Layout.dialog_achievements;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldleft = Tables.Sample.Resource.Layout.dialog_boolfieldleft;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldright = Tables.Sample.Resource.Layout.dialog_boolfieldright;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldsubleft = Tables.Sample.Resource.Layout.dialog_boolfieldsubleft;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldsubright = Tables.Sample.Resource.Layout.dialog_boolfieldsubright;
			Xamarin.Tables.Resource.Layout.dialog_button = Tables.Sample.Resource.Layout.dialog_button;
			Xamarin.Tables.Resource.Layout.dialog_datefield = Tables.Sample.Resource.Layout.dialog_datefield;
			Xamarin.Tables.Resource.Layout.dialog_fieldsetlabel = Tables.Sample.Resource.Layout.dialog_fieldsetlabel;
			Xamarin.Tables.Resource.Layout.dialog_floatimage = Tables.Sample.Resource.Layout.dialog_floatimage;
			Xamarin.Tables.Resource.Layout.dialog_labelfieldbelow = Tables.Sample.Resource.Layout.dialog_labelfieldbelow;
			Xamarin.Tables.Resource.Layout.dialog_labelfieldright = Tables.Sample.Resource.Layout.dialog_labelfieldright;
			Xamarin.Tables.Resource.Layout.dialog_onofffieldright = Tables.Sample.Resource.Layout.dialog_onofffieldright;
			Xamarin.Tables.Resource.Layout.dialog_panel = Tables.Sample.Resource.Layout.dialog_panel;
			Xamarin.Tables.Resource.Layout.dialog_root = Tables.Sample.Resource.Layout.dialog_root;
			Xamarin.Tables.Resource.Layout.dialog_selectlist = Tables.Sample.Resource.Layout.dialog_selectlist;
			Xamarin.Tables.Resource.Layout.dialog_selectlistfield = Tables.Sample.Resource.Layout.dialog_selectlistfield;
			Xamarin.Tables.Resource.Layout.dialog_textarea = Tables.Sample.Resource.Layout.dialog_textarea;
			Xamarin.Tables.Resource.Layout.dialog_textfieldbelow = Tables.Sample.Resource.Layout.dialog_textfieldbelow;
			Xamarin.Tables.Resource.Layout.dialog_textfieldright = Tables.Sample.Resource.Layout.dialog_textfieldright;
			Xamarin.Tables.Resource.Layout.NavListView = Tables.Sample.Resource.Layout.NavListView;
			Xamarin.Tables.Resource.String.library_name = Tables.Sample.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_right = 2130968579;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int LeftBtn = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int LeftButtonLayout = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int LinearLayout01 = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int RightBtn = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int RightButtonLayout = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int dialog_BoolField = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int dialog_Button = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int dialog_DisclosureField = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int dialog_ImageLeft = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ImageRight = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelSubtextField = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int dialog_Panel = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int dialog_RadioButtonList = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int dialog_SliderField = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_Spinner = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int dialog_ValueField = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int iFormFieldValue = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int myButton = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int navContent = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int separator = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int title = 2131099665;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldbelow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labelfieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_onofffieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_root = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_selectlist = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_selectlistfield = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_textarea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_textfieldbelow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_textfieldright = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Main = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int NavListView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SectionedListSeparator = 2130903061;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
