#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.Tables.Resource", IsApplication=false)]

namespace Xamarin.Tables
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int slide_out_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int dialog_expander_ic_minimized = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int LinearLayout01 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public static int dialog_BoolField = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int dialog_Button = 2131099658;
			
			// aapt resource value: 0x7f060010
			public static int dialog_DisclosureField = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public static int dialog_ImageLeft = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public static int dialog_ImageRight = 2131099662;
			
			// aapt resource value: 0x7f060007
			public static int dialog_LabelField = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int dialog_LabelSubtextField = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public static int dialog_Panel = 2131099663;
			
			// aapt resource value: 0x7f060011
			public static int dialog_RadioButtonList = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public static int dialog_SliderField = 2131099661;
			
			// aapt resource value: 0x7f060012
			public static int dialog_Spinner = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public static int dialog_ValueField = 2131099659;
			
			// aapt resource value: 0x7f060013
			public static int iFormFieldValue = 2131099667;
			
			// aapt resource value: 0x7f060003
			public static int title = 2131099651;
			
			// aapt resource value: 0x7f060001
			public static int uinavigationLeftButtonLayout = 2131099649;
			
			// aapt resource value: 0x7f060004
			public static int uinavigationRightButtonLayout = 2131099652;
			
			// aapt resource value: 0x7f060006
			public static int uinavigationcontent = 2131099654;
			
			// aapt resource value: 0x7f060002
			public static int uinavigationleftbtn = 2131099650;
			
			// aapt resource value: 0x7f060005
			public static int uinavigationrightbtn = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int anav = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int dialog_achievements = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int dialog_boolfieldleft = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int dialog_boolfieldright = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int dialog_boolfieldsubleft = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int dialog_boolfieldsubright = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int dialog_button = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int dialog_datefield = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int dialog_fieldsetlabel = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int dialog_floatimage = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int dialog_labelfieldbelow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int dialog_labelfieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int dialog_onofffieldright = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int dialog_panel = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int dialog_root = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int dialog_selectlist = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int dialog_selectlistfield = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int dialog_textarea = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int dialog_textfieldbelow = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int dialog_textfieldright = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
